---
_extends: .github:common-settings.yaml

repository:
  description: Projects and configuration for my ESPHome devices

branches:
  - name: main
    protection:
      required_status_checks:
        strict: false
        contexts: ['Prepare','Build', 'Publish', 'Renovate / Renovate']
      enforce_admins: true
      required_pull_request_reviews: null
      restrictions: null
      required_linear_history: true
