substitutions:
  name: olimex-bluetooth-proxy-13451c
  friendly_name: Bluetooth Proxy 13451c
packages:
  olimex-bluetooth-proxy: github://marcusrbrown/esphome.life/packages/olimex-bluetooth-proxy.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret olimex_bluetooth_proxy_13451c_api_key
