name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, 'renovate/**']
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - project-template-esp32.yaml
          - project-template-esp8266.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@cc3338df37add30f0d4ddc0bf11a98a77c5e2b61 # v1.5.0
        with:
          yaml_file: ${{ matrix.file }}
