name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: olimex-bluetooth-proxy-1349f4.yaml
      name: ESPHome Life
